CREATE TABLE EMPRESA (
    ID NUMBER GENERATED AS IDENTITY CONSTRAINT IDEMPRESA PRIMARY KEY,
    NOME_EMPRESA VARCHAR2(255)
);

CREATE TABLE SETOR (
    ID NUMBER GENERATED AS IDENTITY CONSTRAINT IDSETOR PRIMARY KEY,
    DESCRICAO VARCHAR2(255),
    EMPRESA_ID NUMBER NOT NULL
);

CREATE TABLE USUARIO (
    ID NUMBER GENERATED AS IDENTITY CONSTRAINT IDUSUARIO PRIMARY KEY,
    NOME VARCHAR2(255),
    CARGO VARCHAR2(255),
    SETOR_ID NUMBER NOT NULL
);

CREATE TABLE FUNCIONARIO_INFO (
    ID NUMBER GENERATED AS IDENTITY CONSTRAINT IDFUNCIONARIOINFO PRIMARY KEY,
    DATA DATE,
    HUMOR NUMBER(1),
    ENERGIA NUMBER(1),
    CARGA NUMBER(1),
    SONO NUMBER(1),
    OBSERVACAO VARCHAR2(255),
    HISTORICO_MEDICO VARCHAR2(255),
    USUARIO_ID NUMBER NOT NULL,
    CONSTRAINT FUNCIONARIO_INFO_USUARIO_FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID)
);