ALTER TABLE SETOR
  ADD CONSTRAINT SETOR_EMPRESA_FK
  FOREIGN KEY (EMPRESA_ID) REFERENCES EMPRESA(ID);

ALTER TABLE USUARIO
  ADD CONSTRAINT USUARIO_SETOR_FK
  FOREIGN KEY (SETOR_ID) REFERENCES SETOR(ID);

ALTER TABLE FUNCIONARIO_INFO
  ADD CONSTRAINT FUNCIONARIO_INFO_USUARIO_FK
  FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(ID);

