INSERT INTO EMPRESA (NOME_EMPRESA) VALUES ('Empresa A');
INSERT INTO EMPRESA (NOME_EMPRESA) VALUES ('Empresa B');
INSERT INTO EMPRESA (NOME_EMPRESA) VALUES ('Empresa C');
INSERT INTO EMPRESA (NOME_EMPRESA) VALUES ('Empresa D');
INSERT INTO EMPRESA (NOME_EMPRESA) VALUES ('Empresa E');

INSERT INTO SETOR (DESCRICAO, EMPRESA_ID) VALUES ('Recursos Humanos', 1);
INSERT INTO SETOR (DESCRICAO, EMPRESA_ID) VALUES ('Tecnologia', 1);
INSERT INTO SETOR (DESCRICAO, EMPRESA_ID) VALUES ('Financeiro', 2);
INSERT INTO SETOR (DESCRICAO, EMPRESA_ID) VALUES ('Marketing', 3);
INSERT INTO SETOR (DESCRICAO, EMPRESA_ID) VALUES ('Vendas', 2);

INSERT INTO USUARIO (NOME, SENHA, CARGO, SETOR_ID) VALUES ('João Silva', '$2a$10$cWmYOtcwKUpOu2xNwMdX.ODgeUNd4bCBrNeMLDJYdTlXWeOoO.AS2', 'Analista', 1);
INSERT INTO USUARIO (NOME, SENHA, CARGO, SETOR_ID) VALUES ('Maria Oliveira', '$2a$10$cWmYOtcwKUpOu2xNwMdX.ODgeUNd4bCBrNeMLDJYdTlXWeOoO.AS2', 'Desenvolvedora', 2);
INSERT INTO USUARIO (NOME, SENHA, CARGO, SETOR_ID) VALUES ('Carlos Santos', '$2a$10$cWmYOtcwKUpOu2xNwMdX.ODgeUNd4bCBrNeMLDJYdTlXWeOoO.AS2', 'Contador', 3);
INSERT INTO USUARIO (NOME, SENHA, CARGO, SETOR_ID) VALUES ('Ana Lima', '$2a$10$cWmYOtcwKUpOu2xNwMdX.ODgeUNd4bCBrNeMLDJYdTlXWeOoO.AS2', 'Especialista em Marketing', 4);
INSERT INTO USUARIO (NOME, SENHA, CARGO, SETOR_ID) VALUES ('Fernanda Costa', '$2a$10$cWmYOtcwKUpOu2xNwMdX.ODgeUNd4bCBrNeMLDJYdTlXWeOoO.AS2', 'Vendedora', 5);

INSERT INTO FUNCIONARIO_INFO (DATA, HUMOR, ENERGIA, CARGA, SONO, OBSERVACAO, HISTORICO_MEDICO, USUARIO_ID) VALUES 
(TO_TIMESTAMP('2025-11-10 09:32:10', 'YYYY-MM-DD HH24:MI:SS'), 3, 4, 5, 3, 'Sem observações', 'Nenhum histórico', 1);

INSERT INTO FUNCIONARIO_INFO (DATA, HUMOR, ENERGIA, CARGA, SONO, OBSERVACAO, HISTORICO_MEDICO, USUARIO_ID) VALUES 
(TO_TIMESTAMP('2025-11-11 10:58:42', 'YYYY-MM-DD HH24:MI:SS'), 4, 3, 4, 2, 'Alérgico a pólen', 'Asma leve', 2);

INSERT INTO FUNCIONARIO_INFO (DATA, HUMOR, ENERGIA, CARGA, SONO, OBSERVACAO, HISTORICO_MEDICO, USUARIO_ID) VALUES 
(TO_TIMESTAMP('2025-11-12 14:23:17', 'YYYY-MM-DD HH24:MI:SS'), 2, 4, 3, 4, 'Necessita pausa a cada 2h', 'Hipertensão controlada', 3);

INSERT INTO FUNCIONARIO_INFO (DATA, HUMOR, ENERGIA, CARGA, SONO, OBSERVACAO, HISTORICO_MEDICO, USUARIO_ID) VALUES 
(TO_TIMESTAMP('2025-11-13 16:07:33', 'YYYY-MM-DD HH24:MI:SS'), 5, 5, 5, 5, 'Excelente desempenho', 'Nenhum histórico', 4);

INSERT INTO FUNCIONARIO_INFO (DATA, HUMOR, ENERGIA, CARGA, SONO, OBSERVACAO, HISTORICO_MEDICO, USUARIO_ID) VALUES 
(TO_TIMESTAMP('2025-11-14 08:41:05', 'YYYY-MM-DD HH24:MI:SS'), 3, 3, 4, 3, 'Horário flexível', 'Diabetes tipo 2', 5);